Desktop version of Portfolio
masouma2020/PortfolioDeskVersion pull request #1
Opened 2022-09-02 09:34 UTC by masouma2020

This is a Portfolio in Desktop Version

2022-09-02 09:38 UTC, awais-amjed reviewed
Hi @masouma2020 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

_Kindly add a description to your Pull Request and update your Readme file to match Microverse Readme_ 🤗

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-02 10:37 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @masouma2020 , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 10:37 UTC, awais-amjed commented on index.html
> -          <form class="contantform" method="post" action="https://formspree.io/f/masouma_form_id">
Kindly note the differences in the first section of your webpage as shown below 😃
- _Kindly update the color of the Navigation links_
- _The main heading's weight should be fixed_
- _The space above LET'S CONNECT should be fixed_
- _The color of social icons should be fixed_
- _Also, please make sure that the navigation bar has spacing from the sides as shown in the Figma design_
- _Background image also needs to be fixed. Kindly fix this on mobile design as well_

Your design:

![image](https://user-images.githubusercontent.com/73714615/188117357-8d99df83-bcf4-41c5-ad1f-6ad2f365a47d.png)
![image](https://user-images.githubusercontent.com/73714615/188121781-d8cb4009-44a7-4fda-9eda-74e4573464c6.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/188117185-9708223e-d960-4829-b23c-ddf2e33a921c.png)
![image](https://user-images.githubusercontent.com/73714615/188121842-80a48e70-9433-4412-b2a2-ce164beec604.png)

2022-09-02 10:37 UTC, awais-amjed commented on index.html
> -          <form class="contantform" method="post" action="https://formspree.io/f/masouma_form_id">
Kindly note the differences in the works section and fix them 🤗
  - _The project's description switches places with each project (picture is on the left and description on the right for the first project, description on the left and picture on the right for the second project and so on and so forth)_
  - _Kindly fix the button style to be consistent in all Projects and make it resemble the Figma design_
  - _Kindly note that your works are only taking 85% of the screen space, please make it 100% and make them centered as shown in Figma deisgn_
  - _Kindly also fix the Font weight of the project heading_
  - _Please also check the spacing between elements to resemble the Figma design_

Your design:

![image](https://user-images.githubusercontent.com/73714615/188119687-5064625e-4fac-4156-bfa2-8516937397f7.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/188119774-e9cc8505-27ca-40f1-abf7-ad80322506a9.png)

2022-09-02 10:37 UTC, awais-amjed commented on index.html
> -          <form class="contantform" method="post" action="https://formspree.io/f/masouma_form_id">
Kindly note the differences in your About section and fix them 🤗
  - _The font weight of the heading should be similar to the Figma design_
  - _Kindly update the social icon colors to match the Figma design_
  - _Kindly fix the spacing between elements to match the Figma deisgn_
  - _Please note that the left part of the About section takes 40% and the right one the remaining 60% of the page's width_

Your design:

![image](https://user-images.githubusercontent.com/73714615/188120130-ef0438a1-0d54-4d3e-9986-e448107c8b2d.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/188120523-d08b2564-9f40-442b-b0a4-633101645541.png)

2022-09-02 10:37 UTC, awais-amjed commented on index.html
>            </form>
Kindly add some padding to the input fields and limit the width of the text on the top of the form to make it similar to the Figma design 😀

Your design:

![image](https://user-images.githubusercontent.com/73714615/188120938-92a9eca0-06fc-46ae-b2e0-a7dbc4eeb49a.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/188121308-d44e99fc-087e-492f-bec6-e631f6832cc0.png)

- Kindly also fix the Button text to say "Get in Touch", instead of "Get It Touch". Seems to be a mistake in the Figma design 😅

2022-09-03 10:52 UTC, masouma2020 commented on index.html
> -          <form class="contantform" method="post" action="https://formspree.io/f/masouma_form_id">
Review my code and Hope approve it

2022-09-03 11:53 UTC, emmiiorji approved these changes
Hi @masouma2020, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/188269175-342213cc-f0ae-4b45-b000-41529353dcd1.gif)


## Good Highlights ✅

- Good commit messages
- Linter checks are passing
- PR is descriptive


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-03 13:10 UTC, merged

2022-09-03 13:10 UTC, masouma2020 commented
Task completed